name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [ master ]

env:
  PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
jobs:
  matrix_prep:
    runs-on: ubuntu-18.04
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: ''
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: nelonoel/branch-name@v1.0.1
      - id: set-matrix
        uses: JoshuaTheMiller/conditional-build-matrix@0.0.1
        with:
          filter: '[?runOn==`${{ env.BRANCH_NAME }}` || runOn==`always`]'

  build-n-test:
    needs: matrix_prep
    runs-on: ubuntu-18.04
    strategy:
      matrix: ${{fromJson(needs.matrix_prep.outputs.matrix)}}
      max-parallel: 3
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.py_version }}
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.py_version }}"
      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1
      - name: Install dependencies
        run: |
          pip3 install pipenv
          sed -i 's/3.8/${{ matrix.py_version }}/g' Pipfile
          pipenv install tox
          pipenv install --dev --ignore-pipfile --deploy
      # - name: Install and setup code coverage tool
      #   run: |
      #     curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      #     chmod +x ./cc-test-reporter
      #     ./cc-test-reporter before-build
      #     rm -rf data/
      #     git diff Pipfile
      #     git checkout Pipfile Pipfile.lock
      # - name: Test with pytest
      #   run: |
      #     pipenv run pytest --cov-report xml --cov-report term
      # # Report results back to code climate
      # - name: Report coverage to codeclimate
      #   run: |
      #     ./cc-test-reporter after-build --exit-code 0


  